cv:
	pdflatex cv.tex
report:
	pdflatex report.tex
love:
	pdflatex love.tex
ps:
	pdflatex ps.tex
practise:
	pdflatex practise.tex
calendar:
	pdflatex calendar.tex
ss:
	pdflatex scholarship.tex
proposal:
	pdflatex proposal.tex
	bibtex proposal
	pdflatex proposal.tex
	pdflatex proposal.tex
proposal1:
	pdflatex proposal1.tex
	bibtex proposal1
	pdflatex proposal1.tex
	pdflatex proposal1.tex
proposal8210:
	pdflatex proposal8210.tex
	bibtex proposal8210
	pdflatex proposal8210.tex
	pdflatex proposal8210.tex
preproposal:
	pdflatex preproposal.tex
project1:
	pdflatex project1.tex
project2:
	pdflatex project2.tex
resume:
	pdflatex resume.tex
cover:
	pdflatex cover_letter.tex

clean:
	rm -f *~ *.dvi *.aux *.log *.bbl *.blg *.out *.toc

