cv:
	pdflatex cv.tex
report:
	pdflatex report.tex
love:
	pdflatex love.tex
ps:
	pdflatex ps.tex
ss:
	pdflatex scholarship.tex
proposal:
	pdflatex proposal.tex
	bibtex proposal
	pdflatex proposal.tex
	pdflatex proposal.tex
preproposal:
	pdflatex preproposal.tex
project1:
	pdflatex project1.tex
project2:
	pdflatex project2.tex
resume:
	pdflatex resume.tex

clean:
	rm -f *~ *.dvi *.aux *.log *.bbl *.blg *.out *.toc

